name: anime_news
description: App de notícias de anime com Firebase, notificações e recursos nativos.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP / API
  http: ^1.1.0

  # State management
  provider: ^6.0.5

  # Firebase core + auth + firestore + storage + messaging
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.0.0
  firebase_messaging: ^14.3.0

  # Native features
  image_picker: ^1.2.1
  geolocator: ^9.0.2
  permission_handler: ^10.4.0
  path_provider: ^2.0.14

  # Utilities
  shared_preferences: ^2.1.0
  flutter_local_notifications: ^13.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
