name: filmes_hobby
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  translator: ^1.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.0
  path_provider: ^2.0.14
  image: ^4.0.15
  firebase_core: ^2.24.2  # Substitua 'latest_version' por um número real
  firebase_auth: ^4.15.2  # Substitua 'latest_version' por um número real
  cloud_firestore: ^4.13.5
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
