<<<<<<< HEAD
name: filmes_hobby
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1
=======
name: anime_news
description: App de notícias de anime com Firebase, notificações e recursos nativos.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
>>>>>>> a113246fd4774b5b4e5c187dc01c24d1760ddc16

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  translator: ^1.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.0
  path_provider: ^2.0.14
  image: ^4.0.15
  firebase_core: ^2.24.2  # Substitua 'latest_version' por um número real
  firebase_auth: ^4.15.2  # Substitua 'latest_version' por um número real
  cloud_firestore: ^4.13.5
  
 
=======

  # HTTP / API
  http: ^1.1.0

  # State management
  provider: ^6.0.5

  # Firebase core + auth + firestore + storage + messaging
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.0.0
  firebase_messaging: ^14.3.0

  # Native features
  image_picker: ^1.2.1
  geolocator: ^9.0.2
  permission_handler: ^10.4.0
  path_provider: ^2.0.14

  # Utilities
  shared_preferences: ^2.1.0
  flutter_local_notifications: ^13.0.0
  url_launcher: ^6.3.2
>>>>>>> a113246fd4774b5b4e5c187dc01c24d1760ddc16

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
=======
>>>>>>> a113246fd4774b5b4e5c187dc01c24d1760ddc16
